
import com.sun.media.sound.JARSoundbankReader;
import javax.swing.JFrame;
import java.awt.*;
import java.awt.font.TextAttribute;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.*;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import operations.operations;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author vijay
 */
public class main extends javax.swing.JFrame {

    /**
     * Creates new form main
     */
    String book_type;
    String book_author;
    String book_price;
    String book_name;
    String book_quantity;
    String tname;
    ArrayList<String> rea=new ArrayList<String>();
    String gender;
    public main() {
        initComponents();
        
              /*Font  f1  = new Font(Font.MONOSPACED, Font.PLAIN,  25);
              Font f2=new Font(Font.MONOSPACED, Font.PLAIN,15);
              Font f3=new Font(Font.MONOSPACED,Font.PLAIN,30);
                signupl.setFont(f1);
                cat1.setFont(f2);
                search.setFont(f2);
                //cstock.setFont(f2);
                bs.setFont(f1);
                jLabel5.setFont(f2);*/
                errormsg.setVisible(false);
                
                    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        signupframe = new javax.swing.JFrame();
        signupl = new javax.swing.JLabel();
        uname = new javax.swing.JTextField();
        pass = new javax.swing.JPasswordField();
        sbutton = new javax.swing.JButton();
        rseller = new javax.swing.JRadioButton();
        rcustomer = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        l = new javax.swing.JLabel();
        f = new javax.swing.JLabel();
        c = new javax.swing.JLabel();
        g = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        u = new javax.swing.JLabel();
        fname = new javax.swing.JTextField();
        lname = new javax.swing.JTextField();
        cno = new javax.swing.JTextField();
        rm = new javax.swing.JRadioButton();
        rf = new javax.swing.JRadioButton();
        seller = new javax.swing.JFrame();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        bs = new javax.swing.JLabel();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu16 = new javax.swing.JMenu();
        jMenu13 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        customer = new javax.swing.JFrame();
        cbox = new javax.swing.JComboBox<>();
        cat1 = new javax.swing.JLabel();
        search = new javax.swing.JLabel();
        stext = new javax.swing.JTextField();
        srchbtn = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        bookname = new javax.swing.JLabel();
        booktype = new javax.swing.JLabel();
        bookauthor = new javax.swing.JLabel();
        bookprice = new javax.swing.JLabel();
        purc = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        welcome = new javax.swing.JLabel();
        username = new javax.swing.JLabel();
        errormsg = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        logout = new javax.swing.JMenu();
        checkstock = new javax.swing.JFrame();
        scrollPane1 = new java.awt.ScrollPane();
        jMenuBar3 = new javax.swing.JMenuBar();
        jMenu5 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();
        jMenu8 = new javax.swing.JMenu();
        updatestock = new javax.swing.JFrame();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        bquant = new javax.swing.JTextField();
        bname = new javax.swing.JTextField();
        bprice = new javax.swing.JTextField();
        bauthor = new javax.swing.JTextField();
        bcategory = new javax.swing.JComboBox<>();
        addbook = new javax.swing.JButton();
        msg = new javax.swing.JLabel();
        jMenuBar4 = new javax.swing.JMenuBar();
        jMenu9 = new javax.swing.JMenu();
        jMenu10 = new javax.swing.JMenu();
        jMenu11 = new javax.swing.JMenu();
        jMenu12 = new javax.swing.JMenu();
        buy = new javax.swing.JFrame();
        qun = new javax.swing.JLabel();
        enterqun = new javax.swing.JTextField();
        proceedbut = new javax.swing.JButton();
        placemsg = new javax.swing.JLabel();
        bill = new javax.swing.JLabel();
        butgrp = new javax.swing.ButtonGroup();
        btngrp2 = new javax.swing.ButtonGroup();
        upbook = new javax.swing.JFrame();
        jPanel4 = new javax.swing.JPanel();
        bnametx = new javax.swing.JLabel();
        bauttx = new javax.swing.JLabel();
        bquntx = new javax.swing.JLabel();
        bprtx = new javax.swing.JLabel();
        bqune = new javax.swing.JTextField();
        bnamee = new javax.swing.JTextField();
        bpricee = new javax.swing.JTextField();
        bauthore = new javax.swing.JTextField();
        update = new javax.swing.JButton();
        msg1 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        label1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        suname = new javax.swing.JTextField();
        cuname = new javax.swing.JTextField();
        slogin = new javax.swing.JButton();
        clogin = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        signup = new javax.swing.JButton();
        cpassword = new javax.swing.JPasswordField();
        spassword = new javax.swing.JPasswordField();
        error1 = new javax.swing.JLabel();
        error2 = new javax.swing.JLabel();
        error3 = new javax.swing.JLabel();

        signupframe.setBackground(Color.DARK_GRAY);

        signupl.setFont(new java.awt.Font("Manjari Bold", 0, 24)); // NOI18N
        signupl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        signupl.setText("Sign Up");

        uname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unameActionPerformed(evt);
            }
        });

        sbutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/buttons/button(1).png"))); // NOI18N
        sbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sbuttonActionPerformed(evt);
            }
        });

        butgrp.add(rseller);
        rseller.setText("Seller");
        rseller.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rsellerActionPerformed(evt);
            }
        });

        butgrp.add(rcustomer);
        rcustomer.setText("Customer");
        rcustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rcustomerActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Manjari Bold", 0, 15)); // NOI18N
        jLabel4.setText("Back to Login Page:");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/buttons/button(3).png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        l.setFont(new java.awt.Font("Manjari Bold", 0, 15)); // NOI18N
        l.setText("Last Name:");

        f.setFont(new java.awt.Font("Manjari Bold", 0, 15)); // NOI18N
        f.setText("First Name:");

        c.setFont(new java.awt.Font("Manjari Bold", 0, 15)); // NOI18N
        c.setText("Contact No:");

        g.setFont(new java.awt.Font("Manjari Bold", 0, 15)); // NOI18N
        g.setText("Gender:");

        jLabel9.setFont(new java.awt.Font("Manjari Bold", 0, 15)); // NOI18N
        jLabel9.setText("Password:");

        jLabel10.setFont(new java.awt.Font("Manjari Bold", 0, 15)); // NOI18N
        jLabel10.setText("Select Account Type:");

        u.setFont(new java.awt.Font("Manjari Bold", 0, 15)); // NOI18N
        u.setText("Username:");

        fname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fnameActionPerformed(evt);
            }
        });

        lname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lnameActionPerformed(evt);
            }
        });

        cno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cnoActionPerformed(evt);
            }
        });

        btngrp2.add(rm);
        rm.setText("Male");
        rm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rmActionPerformed(evt);
            }
        });

        btngrp2.add(rf);
        rf.setText("Female");
        rf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rfActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout signupframeLayout = new javax.swing.GroupLayout(signupframe.getContentPane());
        signupframe.getContentPane().setLayout(signupframeLayout);
        signupframeLayout.setHorizontalGroup(
            signupframeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(signupframeLayout.createSequentialGroup()
                .addGroup(signupframeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(signupframeLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(signupframeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(signupframeLayout.createSequentialGroup()
                                .addGap(288, 288, 288)
                                .addGroup(signupframeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(u, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(c, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(g, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(l, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(f, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(38, 38, 38)
                                .addGroup(signupframeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(signupframeLayout.createSequentialGroup()
                                        .addComponent(rseller)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(rcustomer))
                                    .addComponent(pass, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(uname, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cno, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(fname, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(signupframeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(signupframeLayout.createSequentialGroup()
                                            .addComponent(rm)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(rf))
                                        .addComponent(lname, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(signupframeLayout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, signupframeLayout.createSequentialGroup()
                                .addComponent(sbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(110, 110, 110))))
                    .addGroup(signupframeLayout.createSequentialGroup()
                        .addGap(366, 366, 366)
                        .addComponent(signupl, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(188, 367, Short.MAX_VALUE))
        );
        signupframeLayout.setVerticalGroup(
            signupframeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(signupframeLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(signupl, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(signupframeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(f, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(signupframeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(l, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(signupframeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(g, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rm)
                    .addComponent(rf))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(signupframeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(c, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(signupframeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(u, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(uname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(signupframeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addGroup(signupframeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rseller)
                    .addComponent(rcustomer))
                .addGap(18, 18, 18)
                .addComponent(sbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(signupframeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44))
        );

        jLabel5.setFont(new java.awt.Font("Manjari Bold", 0, 18)); // NOI18N
        jLabel5.setText("Welcome To The Store");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(346, 346, 346)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(684, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(340, Short.MAX_VALUE))
        );

        bs.setFont(new java.awt.Font("Manjari Bold", 0, 36)); // NOI18N
        bs.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bs.setText("Ajay Book Store");

        jMenu1.setText("Home");
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenu1MousePressed(evt);
            }
        });
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });
        jMenuBar2.add(jMenu1);

        jMenu2.setText("Check Stock");
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu2MouseClicked(evt);
            }
        });
        jMenuBar2.add(jMenu2);

        jMenu3.setText("Update Stock");
        jMenu3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenu3MousePressed(evt);
            }
        });
        jMenuBar2.add(jMenu3);

        jMenu16.setText("Update Book");
        jMenu16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu16MouseClicked(evt);
            }
        });
        jMenuBar2.add(jMenu16);

        jMenu13.setText("Orders");
        jMenu13.addMenuKeyListener(new javax.swing.event.MenuKeyListener() {
            public void menuKeyPressed(javax.swing.event.MenuKeyEvent evt) {
                jMenu13MenuKeyPressed(evt);
            }
            public void menuKeyReleased(javax.swing.event.MenuKeyEvent evt) {
            }
            public void menuKeyTyped(javax.swing.event.MenuKeyEvent evt) {
            }
        });
        jMenu13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu13MouseClicked(evt);
            }
        });
        jMenuBar2.add(jMenu13);

        jMenu4.setText("Logout");
        jMenu4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenu4MousePressed(evt);
            }
        });
        jMenuBar2.add(jMenu4);

        seller.setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout sellerLayout = new javax.swing.GroupLayout(seller.getContentPane());
        seller.getContentPane().setLayout(sellerLayout);
        sellerLayout.setHorizontalGroup(
            sellerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sellerLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(sellerLayout.createSequentialGroup()
                .addGap(230, 230, 230)
                .addComponent(bs, javax.swing.GroupLayout.PREFERRED_SIZE, 499, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        sellerLayout.setVerticalGroup(
            sellerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sellerLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(bs, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        cbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Poetry", "Biography", "Comics", "Technology", "Magazines" }));
        cbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboxActionPerformed(evt);
            }
        });

        cat1.setFont(new java.awt.Font("Manjari Bold", 0, 15)); // NOI18N
        cat1.setText("Catagories:");

        search.setFont(new java.awt.Font("Manjari Bold", 0, 15)); // NOI18N
        search.setText("Book Name:");

        stext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stextActionPerformed(evt);
            }
        });

        srchbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/buttons/button(5).png"))); // NOI18N
        srchbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                srchbtnActionPerformed(evt);
            }
        });

        bookname.setFont(new java.awt.Font("Manjari Regular", 0, 15)); // NOI18N
        bookname.setText("hfh");

        booktype.setFont(new java.awt.Font("Manjari Regular", 0, 15)); // NOI18N
        booktype.setText("htht");

        bookauthor.setFont(new java.awt.Font("Manjari Regular", 0, 15)); // NOI18N
        bookauthor.setText("ghfh");

        bookprice.setFont(new java.awt.Font("Manjari Regular", 0, 15)); // NOI18N
        bookprice.setText("jLabel7");

        purc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/buttons/button(6).png"))); // NOI18N
        purc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                purcActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Manjari Bold", 0, 15)); // NOI18N
        jLabel7.setText("Book Name:");

        jLabel15.setFont(new java.awt.Font("Manjari Bold", 0, 15)); // NOI18N
        jLabel15.setText("Category:");

        jLabel16.setFont(new java.awt.Font("Manjari Bold", 0, 15)); // NOI18N
        jLabel16.setText("Book Price:");

        jLabel18.setFont(new java.awt.Font("Manjari Bold", 0, 15)); // NOI18N
        jLabel18.setText("Author");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(jLabel7)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 92, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bookprice)
                    .addComponent(booktype, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bookauthor)
                    .addComponent(bookname, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(purc, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(98, 98, 98))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bookname, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(booktype, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bookauthor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bookprice))
                .addGap(18, 18, 18)
                .addComponent(purc, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        welcome.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        welcome.setText("Welcome");

        username.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        errormsg.setText("Book Not Found");

        logout.setText("Log out");
        logout.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        logout.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                logoutMousePressed(evt);
            }
        });
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });
        jMenuBar1.add(logout);

        customer.setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout customerLayout = new javax.swing.GroupLayout(customer.getContentPane());
        customer.getContentPane().setLayout(customerLayout);
        customerLayout.setHorizontalGroup(
            customerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(customerLayout.createSequentialGroup()
                .addGroup(customerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(customerLayout.createSequentialGroup()
                        .addGap(254, 254, 254)
                        .addGroup(customerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cat1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(search, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(customerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbox, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(stext, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(customerLayout.createSequentialGroup()
                        .addGap(278, 278, 278)
                        .addComponent(welcome, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55)
                        .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(customerLayout.createSequentialGroup()
                        .addGap(238, 238, 238)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(customerLayout.createSequentialGroup()
                        .addGap(357, 357, 357)
                        .addComponent(srchbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(errormsg)))
                .addContainerGap(326, Short.MAX_VALUE))
        );
        customerLayout.setVerticalGroup(
            customerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(customerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(customerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(welcome, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(customerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cat1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(customerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(search, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(stext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(customerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(customerLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(srchbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(customerLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(errormsg)))
                .addGap(32, 32, 32)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(161, Short.MAX_VALUE))
        );

        jMenu5.setText("Home");
        jMenu5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenu5MousePressed(evt);
            }
        });
        jMenu5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu5ActionPerformed(evt);
            }
        });
        jMenuBar3.add(jMenu5);

        jMenu6.setText("Check Stock");
        jMenu6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu6MouseClicked(evt);
            }
        });
        jMenuBar3.add(jMenu6);

        jMenu7.setText("Update Stock");
        jMenuBar3.add(jMenu7);

        jMenu8.setText("Logout");
        jMenu8.addMenuKeyListener(new javax.swing.event.MenuKeyListener() {
            public void menuKeyPressed(javax.swing.event.MenuKeyEvent evt) {
                jMenu8MenuKeyPressed(evt);
            }
            public void menuKeyReleased(javax.swing.event.MenuKeyEvent evt) {
            }
            public void menuKeyTyped(javax.swing.event.MenuKeyEvent evt) {
            }
        });
        jMenuBar3.add(jMenu8);

        checkstock.setJMenuBar(jMenuBar3);

        javax.swing.GroupLayout checkstockLayout = new javax.swing.GroupLayout(checkstock.getContentPane());
        checkstock.getContentPane().setLayout(checkstockLayout);
        checkstockLayout.setHorizontalGroup(
            checkstockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(checkstockLayout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(scrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 766, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(96, Short.MAX_VALUE))
        );
        checkstockLayout.setVerticalGroup(
            checkstockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(checkstockLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(scrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(74, Short.MAX_VALUE))
        );

        updatestock.setName("updatestock"); // NOI18N

        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel8.setFont(new java.awt.Font("Manjari Bold", 0, 15)); // NOI18N
        jLabel8.setText("Book Name:");

        jLabel11.setFont(new java.awt.Font("Manjari Bold", 0, 15)); // NOI18N
        jLabel11.setText("Book Author:");

        jLabel12.setFont(new java.awt.Font("Manjari Bold", 0, 15)); // NOI18N
        jLabel12.setText("Book Category:");

        jLabel13.setFont(new java.awt.Font("Manjari Bold", 0, 15)); // NOI18N
        jLabel13.setText("Book Quantity:");

        jLabel14.setFont(new java.awt.Font("Manjari Bold", 0, 15)); // NOI18N
        jLabel14.setText("Book Price:");

        bquant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bquantActionPerformed(evt);
            }
        });

        bcategory.setFont(new java.awt.Font("Manjari Regular", 0, 15)); // NOI18N
        bcategory.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Action", "Comic", "Biography", "Adventure", "Spiritual", "Literature" }));

        addbook.setIcon(new javax.swing.ImageIcon(getClass().getResource("/buttons/button(4).png"))); // NOI18N
        addbook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addbookActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(82, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel11))
                                .addGap(1, 1, 1))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel12)
                                .addComponent(jLabel8)))
                        .addGap(65, 65, 65)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(bquant, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(bcategory, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bname)
                            .addComponent(bauthor)
                            .addComponent(bprice, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(65, 65, 65))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(msg, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(120, 120, 120))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(addbook, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(136, 136, 136))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(bcategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(bauthor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)
                        .addComponent(bprice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23)
                        .addComponent(bquant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(bname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addComponent(jLabel12)
                        .addGap(34, 34, 34)
                        .addComponent(jLabel11)
                        .addGap(33, 33, 33)
                        .addComponent(jLabel14)
                        .addGap(35, 35, 35)
                        .addComponent(jLabel13)))
                .addGap(46, 46, 46)
                .addComponent(addbook, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(msg)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jMenu9.setText("Home");
        jMenu9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenu9MousePressed(evt);
            }
        });
        jMenu9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu9ActionPerformed(evt);
            }
        });
        jMenuBar4.add(jMenu9);

        jMenu10.setText("Check Stock");
        jMenu10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu10MouseClicked(evt);
            }
        });
        jMenuBar4.add(jMenu10);

        jMenu11.setText("Update Stock");
        jMenuBar4.add(jMenu11);

        jMenu12.setText("Logout");
        jMenu12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenu12MousePressed(evt);
            }
        });
        jMenuBar4.add(jMenu12);

        updatestock.setJMenuBar(jMenuBar4);

        javax.swing.GroupLayout updatestockLayout = new javax.swing.GroupLayout(updatestock.getContentPane());
        updatestock.getContentPane().setLayout(updatestockLayout);
        updatestockLayout.setHorizontalGroup(
            updatestockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(updatestockLayout.createSequentialGroup()
                .addGap(247, 247, 247)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(249, Short.MAX_VALUE))
        );
        updatestockLayout.setVerticalGroup(
            updatestockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(updatestockLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        qun.setFont(new java.awt.Font("Manjari Bold", 0, 15)); // NOI18N
        qun.setText(" Quantity to Buy:");

        enterqun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterqunActionPerformed(evt);
            }
        });

        proceedbut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/buttons/button(7).png"))); // NOI18N
        proceedbut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proceedbutActionPerformed(evt);
            }
        });

        placemsg.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        placemsg.setText("Order placed Successfully.....!");

        javax.swing.GroupLayout buyLayout = new javax.swing.GroupLayout(buy.getContentPane());
        buy.getContentPane().setLayout(buyLayout);
        buyLayout.setHorizontalGroup(
            buyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buyLayout.createSequentialGroup()
                .addGroup(buyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(buyLayout.createSequentialGroup()
                        .addGap(348, 348, 348)
                        .addComponent(bill, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(buyLayout.createSequentialGroup()
                        .addGap(264, 264, 264)
                        .addGroup(buyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(buyLayout.createSequentialGroup()
                                .addComponent(qun, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(enterqun, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(placemsg, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(buyLayout.createSequentialGroup()
                        .addGap(345, 345, 345)
                        .addComponent(proceedbut, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(327, Short.MAX_VALUE))
        );
        buyLayout.setVerticalGroup(
            buyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buyLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(buyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(qun, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(enterqun, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addComponent(proceedbut, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(placemsg, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bill, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(75, Short.MAX_VALUE))
        );

        jPanel4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        bnametx.setFont(new java.awt.Font("Manjari Bold", 0, 15)); // NOI18N
        bnametx.setText("Book Name:");

        bauttx.setFont(new java.awt.Font("Manjari Bold", 0, 15)); // NOI18N
        bauttx.setText("Book Author:");

        bquntx.setFont(new java.awt.Font("Manjari Bold", 0, 15)); // NOI18N
        bquntx.setText("Book Quantity:");

        bprtx.setFont(new java.awt.Font("Manjari Bold", 0, 15)); // NOI18N
        bprtx.setText("Book Price:");

        bqune.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bquneActionPerformed(evt);
            }
        });

        bnamee.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                bnameeFocusLost(evt);
            }
        });

        update.setIcon(new javax.swing.ImageIcon(getClass().getResource("/buttons/button(4).png"))); // NOI18N
        update.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(72, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(msg1, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(120, 120, 120))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bnametx)
                            .addComponent(bauttx)
                            .addComponent(bprtx)
                            .addComponent(bquntx))
                        .addGap(70, 70, 70)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bauthore, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(bqune, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
                                .addComponent(bnamee)
                                .addComponent(bpricee, javax.swing.GroupLayout.Alignment.TRAILING)))
                        .addGap(65, 65, 65))))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(137, 137, 137)
                .addComponent(update, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bnametx)
                    .addComponent(bnamee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bauttx)
                    .addComponent(bauthore, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bprtx)
                    .addComponent(bpricee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bquntx)
                    .addComponent(bqune, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60)
                .addComponent(update, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70)
                .addComponent(msg1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout upbookLayout = new javax.swing.GroupLayout(upbook.getContentPane());
        upbook.getContentPane().setLayout(upbookLayout);
        upbookLayout.setHorizontalGroup(
            upbookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(upbookLayout.createSequentialGroup()
                .addGap(192, 192, 192)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel19)
                .addContainerGap(148, Short.MAX_VALUE))
        );
        upbookLayout.setVerticalGroup(
            upbookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(upbookLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(upbookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 445, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19))
                .addContainerGap(119, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(java.awt.Color.red);

        label1.setFont(new java.awt.Font("Manjari Bold", 0, 24)); // NOI18N
        label1.setForeground(new java.awt.Color(1, 1, 1));
        label1.setText("Login Page");
        label1.setAutoscrolls(true);

        jLabel2.setBackground(new java.awt.Color(63, 122, 160));
        jLabel2.setFont(new java.awt.Font("Manjari Bold", 0, 18)); // NOI18N
        jLabel2.setText("Seller's Login");

        jLabel3.setFont(new java.awt.Font("Manjari Bold", 0, 18)); // NOI18N
        jLabel3.setText("Customer's Login");

        suname.setText("cypher");
        suname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sunameActionPerformed(evt);
            }
        });

        cuname.setText("purva");
        cuname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cunameActionPerformed(evt);
            }
        });

        slogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/buttons/button.png"))); // NOI18N
        slogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sloginActionPerformed(evt);
            }
        });

        clogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/buttons/button.png"))); // NOI18N
        clogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cloginActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Manjari Bold", 0, 15)); // NOI18N
        jLabel1.setText("For Sign Up Click Here -->");

        signup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/buttons/button(1).png"))); // NOI18N
        signup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signupActionPerformed(evt);
            }
        });

        cpassword.setText("purva");
        cpassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cpasswordActionPerformed(evt);
            }
        });

        spassword.setText("cypher");
        spassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                spasswordActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(144, 144, 144)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(suname, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spassword, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 336, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(error1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(cpassword, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                        .addComponent(cuname, javax.swing.GroupLayout.Alignment.LEADING)))
                .addGap(98, 98, 98))
            .addGroup(layout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addComponent(error2, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(error3, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(120, 120, 120))
            .addGroup(layout.createSequentialGroup()
                .addGap(255, 255, 255)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(signup, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(168, 168, 168)
                .addComponent(slogin, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(clogin, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(193, 193, 193))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(304, 304, 304))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(suname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cuname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(cpassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(error1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(spassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(error2, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(error3, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(clogin, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(slogin, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(signup, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sunameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sunameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sunameActionPerformed

    private void cunameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cunameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cunameActionPerformed

    private void signupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signupActionPerformed
        // TODO add your handling code here:
        signupframe.setSize(936, 525);
        signupframe.setVisible(true);
        
    }//GEN-LAST:event_signupActionPerformed

    private void unameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_unameActionPerformed

    private void sbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sbuttonActionPerformed
        // TODO add your handling code here:
       String fname=this.fname.getText();
       String lname=this.lname.getText();
       int i=0;
       long cno=0;
       try{ cno=Long.parseLong(this.cno.getText());}
       catch(Exception e){
           i=1;
       }
       String uname=this.uname.getText();
       String pass=String.valueOf(this.pass.getText());operations o=new operations();
       if(i==0){
       String err=o.adds(tname, fname, lname, gender, cno, uname, pass);
       if(err=="error"){
           JOptionPane.showMessageDialog(this,"Username or mobile number already registered"); 
       }
       else{
           JOptionPane.showMessageDialog(this,"Successfully registered"); 
       }
       }
       else
            JOptionPane.showMessageDialog(this,"Enter all information");
    }//GEN-LAST:event_sbuttonActionPerformed

    private void rsellerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rsellerActionPerformed
        // TODO add your handling code here:
      tname="sinfo";
    }//GEN-LAST:event_rsellerActionPerformed

    private void rcustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rcustomerActionPerformed
       tname="cinfo";        // TODO add your handling code here:
    }//GEN-LAST:event_rcustomerActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        signupframe.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void sloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sloginActionPerformed
        // TODO add your handling code here:
        tname="sinfo";
        String name=suname.getText();
        String pass=String.valueOf(spassword.getText());
        operations o=new operations();
        if(o.check(tname,name, pass)){
            seller.setVisible(true);
            seller.setSize(936, 525);
            seller.setVisible(true);
            seller.setSize(936, 525);
        }
        else{
          JOptionPane.showMessageDialog(this,"Invalid Username or Password"); 
        }

    }//GEN-LAST:event_sloginActionPerformed
    
    private void cloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cloginActionPerformed
        // TODO add your handling code here:
        String disp=cuname.getText();
        username.setText(disp);
       tname="cinfo";
        String name=cuname.getText();
        String pass=String.valueOf(cpassword.getText());
        operations o=new operations();
        if(o.check(tname,name, pass)){
            customer.setVisible(true);
            customer.setSize(936, 525);
            jPanel3.setVisible(false);
            username.setVisible(true);
            welcome.setVisible(true);
        }
        else{
            JOptionPane.showMessageDialog(this,"Invalid Username or Password"); 
        }
    
    }//GEN-LAST:event_cloginActionPerformed

    private void fnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fnameActionPerformed

    private void lnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lnameActionPerformed

    private void cnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cnoActionPerformed

    private void rmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rmActionPerformed
          gender="Male";        // TODO add your handling code here:
    }//GEN-LAST:event_rmActionPerformed

    private void rfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rfActionPerformed
  gender="Female";        // TODO add your handling code here:
    }//GEN-LAST:event_rfActionPerformed

    private void cboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboxActionPerformed

    private void stextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stextActionPerformed

    private void logoutMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMousePressed
        // TODO add your handling code here:
        customer.setVisible(false);
    }//GEN-LAST:event_logoutMousePressed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void jMenu1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MousePressed
        // TODO add your handling code here:
       // stock.setVisible(false);
    }//GEN-LAST:event_jMenu1MousePressed

    private void jMenu5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu5MousePressed
        // TODO add your handling code here:
        updatestock.setVisible(false);
    }//GEN-LAST:event_jMenu5MousePressed

    private void jMenu5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu5ActionPerformed

    private void jMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MouseClicked
        // TODO add your handling code here:
         Vector<String> column=new Vector<>();
        column.addElement("BookName");
        column.addElement("BookType");
        column.addElement("BookAuthor");
        column.addElement("BookPrice");
        column.addElement("BookQuantity");
        operations o=new operations();
        Vector<Vector> data=o.stock();
      JTable jTable;
      jTable=new JTable(data,column);
      jTable.setFont(new Font("Manjari",Font.BOLD,13));
    JScrollPane scrollPane = new JScrollPane(jTable);
    JFrame stock=new JFrame();
        stock.add(scrollPane);
        stock.setVisible(true);
        stock.setSize(931,508);
    }//GEN-LAST:event_jMenu2MouseClicked

    private void jMenu9MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu9MousePressed
        // TODO add your handling code here:
        updatestock.setVisible(false);
    }//GEN-LAST:event_jMenu9MousePressed

    private void jMenu9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu9ActionPerformed

    private void jMenu10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu10MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu10MouseClicked

    private void jMenu12MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu12MousePressed
        // TODO add your handling code here:
        updatestock.setVisible(false);
        seller.setVisible(false);
        
    }//GEN-LAST:event_jMenu12MousePressed

    private void jMenu3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu3MousePressed
    updatestock.setVisible(true);
    updatestock.setSize(931,508);// TODO add your handling code here:,
    }//GEN-LAST:event_jMenu3MousePressed

    private void bquantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bquantActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bquantActionPerformed

    private void addbookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addbookActionPerformed
        // TODO add your handling code here:
        String bn=bname.getText();
        String bt=bcategory.getSelectedItem().toString();
        String ba=bauthor.getText();
        int bp=0,bq=0;
        int i=0;
        try{
         bp=Integer.parseInt(bprice.getText());
         bq=Integer.parseInt(bquant.getText());}
        catch(Exception e){
            i=1;
             JOptionPane.showMessageDialog(this,"Enter valid details");
        }
        System.out.println(bn);
        System.out.println(bt);
        System.out.print(msg);
        if(i==0){        
         operations o=new operations();
        String msg=o.addBook(bn, bt, ba, bp, bq);
        JOptionPane.showMessageDialog(this,"Book Succcesfully Added");
        }
        bname.setText("");
        bauthor.setText("");
        bprice.setText("");
        bquant.setText("");
                     
    }//GEN-LAST:event_addbookActionPerformed

    private void spasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_spasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_spasswordActionPerformed

    private void jMenu4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu4MousePressed
        // TODO add your handling code here:
        seller.setVisible(false);
    }//GEN-LAST:event_jMenu4MousePressed

    private void jMenu8MenuKeyPressed(javax.swing.event.MenuKeyEvent evt) {//GEN-FIRST:event_jMenu8MenuKeyPressed
        // TODO add your handling code here:
        seller.setVisible(false);
        checkstock.setVisible(false);
    }//GEN-LAST:event_jMenu8MenuKeyPressed

    private void srchbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_srchbtnActionPerformed
        // TODO add your handling code here:
        errormsg.setVisible(false);
        String cat= cbox.getSelectedItem().toString();
        String book=stext.getText();
        operations o=new operations();
        ArrayList<String> result=new ArrayList<String>();
        result=o.searchbook(cat,book);
        String bn=result.get(0);
        if(bn!="Book Not Found"){
        String bty=result.get(1);
        String baut=result.get(2);
        String bpr=result.get(3);
        String bqun=result.get(4);
        bookname.setText(bn);
        booktype.setText(bty);
        bookauthor.setText(baut);
        bookprice.setText(bpr);
        jPanel3.setVisible(true);
        
        }
        else{
        JOptionPane.showMessageDialog(this,"Book Not Found"); 
            jPanel3.setVisible(false);
            
        }
    }//GEN-LAST:event_srchbtnActionPerformed

    private void purcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_purcActionPerformed
        // TODO add your handling code here:
        buy.setVisible(true);
        buy.setSize(936, 525);
        placemsg.setVisible(false);
        bill.setVisible(false);
    }//GEN-LAST:event_purcActionPerformed

    private void cpasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cpasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cpasswordActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        // TODO add your handling code here:
        customer.setVisible(false);
       // JFrame.setVisible(true);
    }//GEN-LAST:event_logoutActionPerformed

    private void enterqunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterqunActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_enterqunActionPerformed

    private void proceedbutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proceedbutActionPerformed
        // TODO add your handling code here:
        String cname=cuname.getText();
        String q=enterqun.getText();
        int i=1;
        int qu=0;
                try{
                    qu=Integer.parseInt(q);
                }catch(Exception e){i=0;}
        operations o=new operations();
        String tx=stext.getText();
       ArrayList<Integer> l1=new ArrayList<Integer>();
       l1=o.buyit(qu, tx);
       int pp1=l1.get(0);
       int b2=l1.get(1);  
         DateTimeFormatter dtf=DateTimeFormatter.ofPattern("yyyy/MM/dd HH:mm:ss");
            LocalDateTime now=LocalDateTime.now();
            String date=dtf.format(now).toString();
       if(b2==1 && i==1)
       {
           int finalprice=qu*pp1;
          // System.out.print(cname+tx+q+String.valueOf(finalprice));
           o.orders_add(cname,tx,qu,finalprice,date);
                JOptionPane.showMessageDialog(this,"Order Successfully Placed\n Cost"+" "+String.valueOf(finalprice));  
          // bill.setText(finalprice +"Rs");
           bill.setVisible(true);   
       }
       else if(i==0)
       {
          JOptionPane.showMessageDialog(this,"Enter count of book");
                 }
       else{
           JOptionPane.showMessageDialog(this,"Book out of order");
           placemsg.setVisible(false);
          bill.setVisible(false);
          
       }
           
    }//GEN-LAST:event_proceedbutActionPerformed

    private void jMenu6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu6MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu6MouseClicked

    private void bquneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bquneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bquneActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        // TODO add your handling code here:
        String bn=bnamee.getText();
        String a=bauthore.getText();
        String p=bpricee.getText();
        String q=bqune.getText();
       operations o2=new operations();
       int bp=0,q1=0,i=0;
       try{
        bp=Integer.parseInt(p);
        q1=Integer.parseInt(q);}
       catch(Exception e){
           i=1;
           JOptionPane.showMessageDialog(this,"Enter valid book details");  
       }
      //int bp=Integer.parseInt(book_price);
      //int q=Integer.parseInt(book_quantity);
      book_name=bnamee.getText();
      if(i==0){
      o2.updateBook(bn,a,bp,q1);
      JOptionPane.showMessageDialog(this,"Update sucessfully...");  
    }//GEN-LAST:event_updateActionPerformed
    }
    private void bnameeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_bnameeFocusLost
        // TODO add your handling code here:
         
        String bname=bnamee.getText();
        operations o1=new operations();
        rea=o1.upbookdetails(bname);
        
        String book_type=rea.get(0);
        String book_author=rea.get(1);
        String book_price=rea.get(2);
        String book_quantity=rea.get(3);
        //bcategorye.setText(book_type);
        bauthore.setText(book_author);
        bpricee.setText(book_price);
        bqune.setText(book_quantity);
        
    }//GEN-LAST:event_bnameeFocusLost

    private void jMenu16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu16MouseClicked
        // TODO add your handling code here:
        upbook.setVisible(true);
        upbook.setSize(936, 550);
    }//GEN-LAST:event_jMenu16MouseClicked

    private void jMenu13MenuKeyPressed(javax.swing.event.MenuKeyEvent evt) {//GEN-FIRST:event_jMenu13MenuKeyPressed
        // TODO add your handling code here:
     
    }//GEN-LAST:event_jMenu13MenuKeyPressed

    private void jMenu13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu13MouseClicked
        // TODO add your handling code here:
               Vector<String> column=new Vector<>();
        column.addElement("Customer Name");
        column.addElement("Book Name");
        column.addElement("Book Quantity");
        column.addElement("Book Price");
        column.addElement("Date and Time");
        operations o=new operations();
        Vector<Vector> data=o.history();
      JTable jTable;
      jTable=new JTable(data,column);
      jTable.setFont(new Font("Manjari",Font.BOLD,13));
    JScrollPane scrollPane = new JScrollPane(jTable);
    JFrame stock=new JFrame();
        stock.add(scrollPane);
        stock.setVisible(true);
        stock.setSize(931,508);
    }//GEN-LAST:event_jMenu13MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
               /* Create and display the form */
         
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new main().setVisible(true);
            }
        });

        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addbook;
    private javax.swing.JTextField bauthor;
    private javax.swing.JTextField bauthore;
    private javax.swing.JLabel bauttx;
    private javax.swing.JComboBox<String> bcategory;
    private javax.swing.JLabel bill;
    private javax.swing.JTextField bname;
    private javax.swing.JTextField bnamee;
    private javax.swing.JLabel bnametx;
    private javax.swing.JLabel bookauthor;
    private javax.swing.JLabel bookname;
    private javax.swing.JLabel bookprice;
    private javax.swing.JLabel booktype;
    private javax.swing.JTextField bprice;
    private javax.swing.JTextField bpricee;
    private javax.swing.JLabel bprtx;
    private javax.swing.JTextField bquant;
    private javax.swing.JTextField bqune;
    private javax.swing.JLabel bquntx;
    private javax.swing.JLabel bs;
    private javax.swing.ButtonGroup btngrp2;
    private javax.swing.ButtonGroup butgrp;
    private javax.swing.JFrame buy;
    private javax.swing.JLabel c;
    private javax.swing.JLabel cat1;
    private javax.swing.JComboBox<String> cbox;
    private javax.swing.JFrame checkstock;
    private javax.swing.JButton clogin;
    private javax.swing.JTextField cno;
    private javax.swing.JPasswordField cpassword;
    private javax.swing.JTextField cuname;
    private javax.swing.JFrame customer;
    private javax.swing.JTextField enterqun;
    private javax.swing.JLabel error1;
    private javax.swing.JLabel error2;
    private javax.swing.JLabel error3;
    private javax.swing.JLabel errormsg;
    private javax.swing.JLabel f;
    private javax.swing.JTextField fname;
    private javax.swing.JLabel g;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu11;
    private javax.swing.JMenu jMenu12;
    private javax.swing.JMenu jMenu13;
    private javax.swing.JMenu jMenu16;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuBar jMenuBar3;
    private javax.swing.JMenuBar jMenuBar4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel l;
    public javax.swing.JLabel label1;
    private javax.swing.JTextField lname;
    private javax.swing.JMenu logout;
    private javax.swing.JLabel msg;
    private javax.swing.JLabel msg1;
    private javax.swing.JPasswordField pass;
    private javax.swing.JLabel placemsg;
    private javax.swing.JButton proceedbut;
    private javax.swing.JButton purc;
    private javax.swing.JLabel qun;
    private javax.swing.JRadioButton rcustomer;
    private javax.swing.JRadioButton rf;
    private javax.swing.JRadioButton rm;
    private javax.swing.JRadioButton rseller;
    private javax.swing.JButton sbutton;
    private java.awt.ScrollPane scrollPane1;
    private javax.swing.JLabel search;
    private javax.swing.JFrame seller;
    private javax.swing.JButton signup;
    private javax.swing.JFrame signupframe;
    private javax.swing.JLabel signupl;
    private javax.swing.JButton slogin;
    private javax.swing.JPasswordField spassword;
    private javax.swing.JButton srchbtn;
    private javax.swing.JTextField stext;
    private javax.swing.JTextField suname;
    private javax.swing.JLabel u;
    private javax.swing.JTextField uname;
    private javax.swing.JFrame upbook;
    private javax.swing.JButton update;
    private javax.swing.JFrame updatestock;
    private javax.swing.JLabel username;
    private javax.swing.JLabel welcome;
    // End of variables declaration//GEN-END:variables

    
}
